{
    "formatVersion": "1.1",
    "component": {
        "group": "com.testrockappreact",
        "module": "testrockapp",
        "version": "0.0.1-local",
        "attributes": {
            "org.gradle.status": "release"
        }
    },
    "createdBy": {
        "gradle": {
            "version": "8.14.3"
        }
    },
    "variants": [
        {
            "name": "debugVariantDefaultApiPublication",
            "attributes": {
                "com.android.build.api.attributes.BuildTypeAttr": "debug",
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.libraryelements": "aar",
                "org.gradle.usage": "java-api"
            },
            "dependencies": [
                {
                    "group": "com.facebook.react",
                    "module": "react-android",
                    "version": {
                        "requires": "0.81.1"
                    }
                },
                {
                    "group": "com.facebook.react",
                    "module": "hermes-android",
                    "version": {
                        "requires": "0.81.1"
                    }
                },
                {
                    "group": "io.coil-kt.coil3",
                    "module": "coil",
                    "version": {
                        "requires": "3.0.4"
                    }
                },
                {
                    "group": "io.coil-kt.coil3",
                    "module": "coil-network-okhttp",
                    "version": {
                        "requires": "3.0.4"
                    }
                },
                {
                    "group": "io.coil-kt.coil3",
                    "module": "coil-svg",
                    "version": {
                        "requires": "3.0.4"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-stdlib",
                    "version": {
                        "requires": "2.1.20"
                    }
                }
            ],
            "files": [
                {
                    "name": "testrockapp-0.0.1-local-debug.aar",
                    "url": "testrockapp-0.0.1-local-debug.aar",
                    "size": 4828016,
                    "sha512": "46cfccfa10d3e0f2e1b85534788d605c86e3bfe290fd4802e02b3acefe0cbe2a9efd2404a66800856aa65cc7d60ae78b97b2ae9adb347ba92fad7421a0d7c978",
                    "sha256": "a124c8b65b635b636c1005ce8b0834fb6c58f35094bdb0ea862dc0d5fd023eaa",
                    "sha1": "8b09eb0324920c89c2e6bb705f86530ea19e1bad",
                    "md5": "a9d9ce0f92cd1a9a296ccdcb55241f9b"
                }
            ]
        },
        {
            "name": "debugVariantDefaultRuntimePublication",
            "attributes": {
                "com.android.build.api.attributes.BuildTypeAttr": "debug",
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.libraryelements": "aar",
                "org.gradle.usage": "java-runtime"
            },
            "dependencies": [
                {
                    "group": "com.facebook.react",
                    "module": "react-android",
                    "version": {
                        "requires": "0.81.1"
                    }
                },
                {
                    "group": "com.facebook.react",
                    "module": "hermes-android",
                    "version": {
                        "requires": "0.81.1"
                    }
                },
                {
                    "group": "io.coil-kt.coil3",
                    "module": "coil",
                    "version": {
                        "requires": "3.0.4"
                    }
                },
                {
                    "group": "io.coil-kt.coil3",
                    "module": "coil-network-okhttp",
                    "version": {
                        "requires": "3.0.4"
                    }
                },
                {
                    "group": "io.coil-kt.coil3",
                    "module": "coil-svg",
                    "version": {
                        "requires": "3.0.4"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-stdlib",
                    "version": {
                        "requires": "2.1.20"
                    }
                }
            ],
            "files": [
                {
                    "name": "testrockapp-0.0.1-local-debug.aar",
                    "url": "testrockapp-0.0.1-local-debug.aar",
                    "size": 4828016,
                    "sha512": "46cfccfa10d3e0f2e1b85534788d605c86e3bfe290fd4802e02b3acefe0cbe2a9efd2404a66800856aa65cc7d60ae78b97b2ae9adb347ba92fad7421a0d7c978",
                    "sha256": "a124c8b65b635b636c1005ce8b0834fb6c58f35094bdb0ea862dc0d5fd023eaa",
                    "sha1": "8b09eb0324920c89c2e6bb705f86530ea19e1bad",
                    "md5": "a9d9ce0f92cd1a9a296ccdcb55241f9b"
                }
            ]
        },
        {
            "name": "releaseVariantDefaultApiPublication",
            "attributes": {
                "com.android.build.api.attributes.BuildTypeAttr": "release",
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.libraryelements": "aar",
                "org.gradle.usage": "java-api"
            },
            "dependencies": [
                {
                    "group": "com.facebook.react",
                    "module": "react-android",
                    "version": {
                        "requires": "0.81.1"
                    }
                },
                {
                    "group": "com.facebook.react",
                    "module": "hermes-android",
                    "version": {
                        "requires": "0.81.1"
                    }
                },
                {
                    "group": "io.coil-kt.coil3",
                    "module": "coil",
                    "version": {
                        "requires": "3.0.4"
                    }
                },
                {
                    "group": "io.coil-kt.coil3",
                    "module": "coil-network-okhttp",
                    "version": {
                        "requires": "3.0.4"
                    }
                },
                {
                    "group": "io.coil-kt.coil3",
                    "module": "coil-svg",
                    "version": {
                        "requires": "3.0.4"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-stdlib",
                    "version": {
                        "requires": "2.1.20"
                    }
                }
            ],
            "files": [
                {
                    "name": "testrockapp-0.0.1-local-release.aar",
                    "url": "testrockapp-0.0.1-local-release.aar",
                    "size": 2505591,
                    "sha512": "298c620377f4e5483bb19899ccb5275086a9a571fd1d95e87138f648fa46e0fa4064ea6b6da9b7a57346360bd5cacf26b1cf61c52e5d9a6a5b50ccd7c1b798b8",
                    "sha256": "a380447d49f915846644e74914ac5acd1b2a83552bd3dc60717fbbb44ad839ee",
                    "sha1": "e7583a0ebf8587b6043c17e26c721f841b4ad95a",
                    "md5": "1b36845d3170026dba7ccbba74857455"
                }
            ]
        },
        {
            "name": "releaseVariantDefaultRuntimePublication",
            "attributes": {
                "com.android.build.api.attributes.BuildTypeAttr": "release",
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.libraryelements": "aar",
                "org.gradle.usage": "java-runtime"
            },
            "dependencies": [
                {
                    "group": "com.facebook.react",
                    "module": "react-android",
                    "version": {
                        "requires": "0.81.1"
                    }
                },
                {
                    "group": "com.facebook.react",
                    "module": "hermes-android",
                    "version": {
                        "requires": "0.81.1"
                    }
                },
                {
                    "group": "io.coil-kt.coil3",
                    "module": "coil",
                    "version": {
                        "requires": "3.0.4"
                    }
                },
                {
                    "group": "io.coil-kt.coil3",
                    "module": "coil-network-okhttp",
                    "version": {
                        "requires": "3.0.4"
                    }
                },
                {
                    "group": "io.coil-kt.coil3",
                    "module": "coil-svg",
                    "version": {
                        "requires": "3.0.4"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-stdlib",
                    "version": {
                        "requires": "2.1.20"
                    }
                }
            ],
            "files": [
                {
                    "name": "testrockapp-0.0.1-local-release.aar",
                    "url": "testrockapp-0.0.1-local-release.aar",
                    "size": 2505591,
                    "sha512": "298c620377f4e5483bb19899ccb5275086a9a571fd1d95e87138f648fa46e0fa4064ea6b6da9b7a57346360bd5cacf26b1cf61c52e5d9a6a5b50ccd7c1b798b8",
                    "sha256": "a380447d49f915846644e74914ac5acd1b2a83552bd3dc60717fbbb44ad839ee",
                    "sha1": "e7583a0ebf8587b6043c17e26c721f841b4ad95a",
                    "md5": "1b36845d3170026dba7ccbba74857455"
                }
            ]
        }
    ]
}